// This file is auto-generated by the Supabase CLI.
// It represents the schema of your database.
// It is recommended to run `supabase gen types typescript --local > database.types.ts` to keep it up to date.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          updated_at: string | null
          email: string | null
          points: number
          country_code: string | null
          postal_code: string | null
        }
        Insert: {
          id: string
          updated_at?: string | null
          email?: string | null
          points?: number
          country_code?: string | null
          postal_code?: string | null
        }
        Update: {
          id?: string
          updated_at?: string | null
          email?: string | null
          points?: number
          country_code?: string | null
          postal_code?: string | null
        }
        Relationships: []
      }
      withdrawal_requests: {
        Row: {
          id: string
          created_at: string
          user_id: string
          paypal_email: string
          points: number
          amount_usd: number
          status: "Pending Review" | "Processed" | "Rejected"
          rejection_reason: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          user_id: string
          paypal_email: string
          points: number
          amount_usd: number
          status: "Pending Review" | "Processed" | "Rejected"
          rejection_reason?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          user_id?: string
          paypal_email?: string
          points?: number
          amount_usd?: number
          status?: "Pending Review" | "Processed" | "Rejected"
          rejection_reason?: string | null
        }
        Relationships: [
            {
              foreignKeyName: "withdrawal_requests_user_id_fkey"
              columns: ["user_id"]
              referencedRelation: "profiles"
              referencedColumns: ["id"]
            }
          ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
