# This tells Netlify which directory to publish.
# For many React projects, this is 'build'. For others (like Vite), it might be 'dist'.
# If your build process outputs to a different folder, change "build" to that folder's name.

[build]
publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Removed incorrect SPA redirect for Next.js
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200